version: '3.3'
services:
  db:
    container_name: employee-management
    image: mysql:8.0-debian
    restart: on-failure
    environment:
      MYSQL_DATABASE: 'employee-management'
      # Password for root access
      MYSQL_ROOT_PASSWORD: 'root'
    ports:
      - '3308:3306'
    expose:
      # Opens port 3306 on the container
      - '3308'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
    # Names our volume
volumes:
  my-db:
